import Header from "@/components/Header/header";
import "@/styles/global.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { montserrat, roboto } from "@/fonts";
import { availableLocales } from "@/utils/i18n";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function generateStaticParams() {
	return availableLocales.map((locale) => ({ locale }));
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} ${montserrat.variable}`}>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	);
}
